import { clientOptionsFromConnection } from '@1c-odata/client'
import config from '../1c-odata.config.js'
import { createClient as createDefaultClient } from '../generated/default/client.js'

/**
 * Build the typed OData client for the `default` connection. After cluster
 * C-2, `defineConfig` preserves the literal `connections.default` key, so no
 * `if (!conn) throw` guard is needed.
 *
 * `createDefaultClient` is generated by codegen (`generated/default/client.ts`)
 * — auto-loads sibling `__metadata.json` and wires the `<Functions>` generic.
 * After `await`, `client.functions.*` is fully typed.
 *
 * Prerequisite: run `pnpm -F basic-example generate` to create the `generated/`
 * folder (offline — reads committed `metadata/default.xml`; only `fetch` and
 * `demo` need `ONEC_EXAMPLE_BASIC_URL`). The `predemo` hook in `package.json`
 * already triggers `generate` before `pnpm demo`.
 */
export async function createClient() {
  return createDefaultClient(clientOptionsFromConnection(config.connections.default))
}
