import { clientOptionsFromConnection } from '@1c-odata/client'
import { createClient as createDefaultClient } from '../generated/default/client.js'
import { defaultConnection } from './connections.js'

/**
 * Build the typed OData client for the `default` connection.
 *
 * The runtime builds its `Connection` from `src/connections.ts` — it does NOT
 * import `1c-odata.config.ts`, which exists only for the `1c-odata` CLI
 * (`fetch` + `generate`). Build-time config and runtime config stay separate.
 *
 * `createDefaultClient` is generated by codegen (`generated/default/client.ts`)
 * — auto-loads sibling `__metadata.json` and wires the `<Functions>` generic.
 * After `await`, `client.functions.*` is fully typed.
 *
 * Prerequisite: run `pnpm -F basic-example generate` to create the `generated/`
 * folder (offline — reads committed `metadata/default.xml`; only `fetch` and
 * `demo` need `ONEC_EXAMPLE_BASIC_URL`). The `predemo` hook in `package.json`
 * already triggers `generate` before `pnpm demo`.
 */
export async function createClient() {
  return createDefaultClient(clientOptionsFromConnection(defaultConnection))
}
