import { describe, expect, it } from 'vitest'
import { emitEnumsFile } from '../../../src/codegen/emitter/enums.js'
import type { EdmxEnumType } from '../../../src/codegen/parser/ast.js'

describe('emitEnumsFile', () => {
  it('emits a header comment + a const + type alias for a single enum', () => {
    const enums: EdmxEnumType[] = [
      {
        name: 'СтатусыЗаказовПоставщикам',
        underlyingType: 'Edm.Int32',
        members: [{ name: 'Закрыт' }, { name: 'НеСогласован' }, { name: 'Подтвержден' }, { name: 'Согласован' }],
      },
    ]
    const { code, warnings } = emitEnumsFile(enums)
    expect(code).toContain('// Auto-generated by @1c-odata/cli. DO NOT EDIT.')
    expect(code).toContain('export const СтатусыЗаказовПоставщикам = {')
    expect(code).toContain(`'Закрыт': 'Закрыт',`)
    expect(code).toContain(`'НеСогласован': 'НеСогласован',`)
    expect(code).toContain(`'Подтвержден': 'Подтвержден',`)
    expect(code).toContain(`'Согласован': 'Согласован',`)
    expect(code).toContain('} as const')
    expect(code).toContain(
      'export type СтатусыЗаказовПоставщикам =\n  (typeof СтатусыЗаказовПоставщикам)[keyof typeof СтатусыЗаказовПоставщикам]',
    )
    expect(warnings).toEqual([])
  })

  it('preserves member order from EDMX (implicit value index)', () => {
    const enums: EdmxEnumType[] = [
      {
        name: 'X',
        underlyingType: 'Edm.Int32',
        members: [{ name: 'B' }, { name: 'A' }, { name: 'C' }],
      },
    ]
    const { code } = emitEnumsFile(enums)
    const idxB = code.indexOf(`'B':`)
    const idxA = code.indexOf(`'A':`)
    const idxC = code.indexOf(`'C':`)
    expect(idxB).toBeGreaterThan(0)
    expect(idxA).toBeGreaterThan(idxB)
    expect(idxC).toBeGreaterThan(idxA)
  })

  it('sorts enums alphabetically by name for deterministic output', () => {
    const enums: EdmxEnumType[] = [
      { name: 'Zeta', underlyingType: 'Edm.Int32', members: [{ name: 'M' }] },
      { name: 'Alpha', underlyingType: 'Edm.Int32', members: [{ name: 'N' }] },
    ]
    const { code } = emitEnumsFile(enums)
    expect(code.indexOf('export const Alpha')).toBeLessThan(code.indexOf('export const Zeta'))
  })

  it('skips enums with zero members and surfaces a warning', () => {
    const enums: EdmxEnumType[] = [
      { name: 'Empty', underlyingType: 'Edm.Int32', members: [] },
      { name: 'Real', underlyingType: 'Edm.Int32', members: [{ name: 'A' }] },
    ]
    const { code, warnings } = emitEnumsFile(enums)
    expect(code).not.toContain('export const Empty')
    expect(code).toContain('export const Real')
    expect(warnings).toEqual(['skipping EnumType "Empty" — zero members'])
  })

  it('quotes member names with special characters', () => {
    const enums: EdmxEnumType[] = [
      {
        name: 'X',
        underlyingType: 'Edm.Int32',
        members: [{ name: 'has space' }, { name: 'normal' }],
      },
    ]
    const { code } = emitEnumsFile(enums)
    expect(code).toContain(`'has space': 'has space',`)
    expect(code).toContain(`'normal': 'normal',`)
  })

  it('refuses to emit an enum whose name is not a valid TS identifier', () => {
    const enums: EdmxEnumType[] = [{ name: 'has-hyphen', underlyingType: 'Edm.Int32', members: [{ name: 'A' }] }]
    expect(() => emitEnumsFile(enums)).toThrow(/invalid TypeScript identifier/i)
  })

  it('returns empty body when no enums survive filtering', () => {
    const { code, warnings } = emitEnumsFile([])
    expect(code).toBe(`// Auto-generated by @1c-odata/cli. DO NOT EDIT.\nexport {}\n`)
    expect(warnings).toEqual([])
  })

  it('escapes single quotes inside member names', () => {
    const enums: EdmxEnumType[] = [{ name: 'X', underlyingType: 'Edm.Int32', members: [{ name: "it's" }] }]
    const { code } = emitEnumsFile(enums)
    expect(code).toContain(`'it\\'s': 'it\\'s',`)
  })

  it('skips duplicate EnumType names (1С trade.xml ships AllowedLength twice)', () => {
    const enums: EdmxEnumType[] = [
      { name: 'AllowedLength', underlyingType: 'Edm.Int32', members: [{ name: 'First' }] },
      { name: 'AllowedLength', underlyingType: 'Edm.Int32', members: [{ name: 'Second' }] },
    ]
    const { code, warnings } = emitEnumsFile(enums)
    // Only the FIRST declaration survives — TS rejects redeclared block-scoped vars.
    const firstIdx = code.indexOf('export const AllowedLength')
    expect(firstIdx).toBeGreaterThan(0)
    expect(code.indexOf('export const AllowedLength', firstIdx + 1)).toBe(-1)
    expect(code).toContain(`'First': 'First',`)
    expect(code).not.toContain(`'Second': 'Second',`)
    expect(warnings).toEqual(['skipping duplicate EnumType "AllowedLength" — keeping first occurrence'])
  })
})
