import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { generate } from '../../../src/codegen/emitter/coordinator.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const FIXTURE = join(__dirname, '../fixtures/09-enum-and-complex.xml')

describe('coordinator emits enums.ts', () => {
  it('produces enums.ts with const + type per EnumType in the fixture', () => {
    const xml = readFileSync(FIXTURE, 'utf8')
    const { files } = generate({ metadata: xml })
    const enumsTs = files.get('enums.ts')
    expect(enumsTs).toBeDefined()
    expect(enumsTs).toContain('// Auto-generated by @1c-odata/cli. DO NOT EDIT.')
    expect(enumsTs).toContain('export const ВидНоменклатуры = {')
    expect(enumsTs).toContain("'Товар': 'Товар',")
    expect(enumsTs).toContain("'Услуга': 'Услуга',")
    expect(enumsTs).toContain('} as const')
    expect(enumsTs).toContain('export type ВидНоменклатуры =')
  })

  it('omits enums.ts entirely when EDMX has zero EnumType declarations', () => {
    const xml = `<?xml version="1.0"?><edmx:Edmx xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx" Version="1.0"><edmx:DataServices xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><Schema Namespace="StandardODATA" xmlns="http://schemas.microsoft.com/ado/2009/11/edm"><EntityType Name="Catalog_X"><Key><PropertyRef Name="Ref_Key"/></Key><Property Name="Ref_Key" Type="Edm.Guid"/></EntityType><EntityContainer Name="StandardODATA" m:IsDefaultEntityContainer="true"><EntitySet Name="Catalog_X" EntityType="StandardODATA.Catalog_X"/></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>`
    const { files } = generate({ metadata: xml })
    expect(files.has('enums.ts')).toBe(false)
  })

  it('produced enums.ts re-exported by master index.ts', () => {
    const xml = readFileSync(FIXTURE, 'utf8')
    const { files } = generate({ metadata: xml })
    const indexTs = files.get('index.ts')
    expect(indexTs).toBeDefined()
    expect(indexTs).toContain(`export * from './enums.js'`)
  })
})
